---
name: 'Metrics'
on:
  - pull_request
  - push
#  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch: { event: 'push' }

jobs:
  achievements:
    runs-on: ubuntu-latest
    steps:
    - name: 'Metrics terminal'
      uses: a-nldisr/metrics@v3.22
      with:
        template: terminal
        filename: terminal.svg
        token: ${{ secrets.METRICS_TOKEN }}
        base: header, metadata