---
name: 'Metrics'
on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch: {}

jobs:
  achievements:
    runs-on: ubuntu-latest
    steps:
    - name: Metrics embed
      uses: a-nldisr/metrics@v3.22
      with:
        template: terminal
        filename: terminal.svg
        token: ${{ secrets.METRICS_TOKEN }}
        base: header, metadata